### ISSUE TITLE
Error: yaml: unsupported node <[l2// field "schemata" not found] _|_> (*ast.BottomLit)

### ISSUE THREAD

**Issue by magick93** [cueblox/blox#110]
# Schema

I've created the following custom schema:

```
{
    _schema: {
        name:      "Book"
        namespace: "schemas.cueblox.com"
    }
    #Book: {
        _dataset: {
            plural: "books"
            supportedExtensions: ["yaml", "yml"]
        }
        name: string
        url?: string

        hungry: bool | *false
    }
}
```

# Steps to reproduce

1. put the above schema into `schemata/book.cue`
2. run `blox new --dataset book bookone`

This results in `Error: yaml: unsupported node <[l2// field "schemata" not found] _|_> (*ast.BottomLit)`.

Please let me know if I'm making a mistake somewhere.

Thanks

# Version info

```
blox version blox version 0.7.0
commit: 9eb0acd273f0fe346d0bb5922087bd910e2e00dc
built at: 2021-09-07T10:20:02Z
built by: goreleaser
```

# Debug output

```
blox new --dataset book bookone --debug
  DEBUG                 Schemata Directory: schemata
  DEBUG                 Loading Schema: schemata/book.cue
  DEBUG                         Next field
  DEBUG                         {
                name:   string
                hungry: false
          }
 INFO  Creating new #book at data/books/bookone.yaml
Error: yaml: unsupported node <[l2// field "schemata" not found] _|_> (*ast.BottomLit)
```

**Comment by rawkode** [comment]
@magick93 do you have a `blox.cue` config? Can you share that too, please?

You can also generate one with `blox init`

**Comment by magick93** [comment]
Yes, certainly.

# blox.cue

```
{
  build_dir:    "_build"
  data_dir:     "data"
  schemata_dir: "schemata"
  static_dir: "static"
}
```

And yes I did use `blox init`.

**Comment by rawkode** [comment]
Thanks. I'll reproduce and get back to you.

**Comment by bketelsen** [comment]
This error is caused if there are no `@template` tags in the cue definition.  Adding one causes the command to succeed. @rawkode I think this worked previously without template tags, so it's likely a bug.

**Comment by magick93** [comment]
I see. Thanks @bketelsen 

When looking at https://github.com/cueblox/blox/blob/main/dogfood/schemata/page_v1.cue#L13-L16 the uses of `@template` looks more like a default value. 

What is difference between a default val and the use of `@template`?

**Comment by bketelsen** [comment]
the `@template` tag is used only for the `blox new` command to generate placeholder text. Default values will be evaluated if a field is empty or not present during the rendering process.

**Comment by magick93** [comment]
Got it, thanks.

Ok, I'll close this issue now. But I'll throw in a quick idea / feature request. 

A `blox new -i book` for interactive would be cool. Then the `@template` annotations could be used to interactively ask for input from the cli.

**Comment by rawkode** [comment]
We actually have a branch with -i working. I'll clean it I!
