### ISSUE TITLE
"make all" build fails

### ISSUE THREAD

**Issue by vielmetti** [cueblox/blox#69]
Trying to build this with `make all` in the home directory of the download. A bunch
of dependencies build, but it looks for "main.go" which it fails to get with this odd lookup:

```txt
go: finding module for package main.go
can't load package: cannot find module providing package main.go: unrecognized import
 path "main.go": https fetch: Get "https://main.go/?go-get=1": dial tcp: lookup main.
go on 100.100.100.100:53: no such host
make: *** [Makefile:21: all] Error 1
```

Environment: Ubuntu 20.10 on Pi 400, go version go1.14.7 linux/arm64. Last commit
was https://github.com/cueblox/blox/commit/d0de6ac74aa273d89e1629529fe7e400d14bee43

**Comment by rawkode** [comment]
@vielmetti I believe this has been fixed
