### ISSUE TITLE
minimum version of go required; older version fails with "make all: cannot load embed"

### ISSUE THREAD

**Issue by vielmetti** [cueblox/blox#84]
`make all` fails with this error

```
build github.com/cueblox/blox/cli/blox: cannot load embed: malformed module path "embed": missing dot in first path element
```

Environment is 

```
> go version
go version go1.13.8 linux/amd64
```

(do I need a newer Go?)

**Comment by rawkode** [comment]
@vielmetti Yes, Go 1.16 is minimum I'm afraid. We should make this more clear

**Comment by bketelsen** [comment]
the minimum go version is already specified in the go.mod file

**Comment by bketelsen** [comment]
@vielmetti can we close this? Do you have a specific need for an older version of go?

**Comment by vielmetti** [comment]
OK to close, it was primarily a documentation issue.
